import React from 'react';
import { FileText, Download, X, CheckCircle2, AlertTriangle, ShieldCheck, Copy, Layers } from 'lucide-react';

export function IntelligenceReport({ open, onClose, _repoReport }) {
  if (!open) return null;

  const downloadReport = () => {
    const text = `# PROJECT CODE INTELLIGENCE REPORT — ShopSphere
Generated by Project Twin / TwinSpace

## 1. Executive Summary
ShopSphere repository is in healthy status (Readiness: 88/100) with 0 breaking API regressions.

## 2. Repository Statistics
- Files: 428
- Lines of Code: 61,240
- Languages: 8 (TypeScript, SQL, HTML/CSS, Dockerfile, Python, Go, JS, Rust)
- Dependencies: 46
- APIs: 38
- Services: 12
- Contributors: 24
- Branches: 6

## 3. Contributors
- Vikash L (Owner & Senior Architect)
- Priya Sharma (Lead Developer)
- Rahul Verma (Full-Stack Engineer)
- Kavin Kumar (Backend Engineer)
- Arun Patel (Tech Lead & Security Reviewer)

## 4. Branches
- main (Default, Protected)
- feature/authentication
- feature/payment-validation
- bugfix/login-error

## 5. Duplicate Code Analysis
- Level 4 Functional Duplication (87% similarity): PaymentValidator.ts (lines 1-6) vs OrderValidator.ts (lines 1-6).
- Recommendation: Extract shared parameter validation into ValidationService.

## 6. Code Quality
- Test Coverage: 63%
- Duplicate Ratio: 2.1%

## 7. Architecture
- React Client → Express REST API → PostgreSQL Database

## 8. Dependencies
- express ^4.19.2, jsonwebtoken ^9.0.2, pg ^8.11.5

## 9. Change Impact
- AuthService changes affect 18 frontend components, 7 APIs, 12 test suites.

## 10. Git History
- Commit a83f21c: Update payment validation logic (Rahul)
- Commit 71b92de: Refactor payment API session validation (Priya)

## 11. Security Indicators
- JWT Token Expiration configured.
- Protected environment secrets: DATABASE_URL, JWT_SECRET.

## 12. Testing Indicators
- 9 passing integration test suites.

## 13. High Priority Findings
- Add VITE_API_URL to production build environment.

## 14. Recommendations
- Extract duplicate validation functions into ValidationService.
`;
    const blob = new Blob([text], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ShopSphere_Project_Code_Intelligence_Report.md';
    a.click();
  };

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.85)', zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <div style={{ background: '#161b22', border: '1px solid #30363d', borderRadius: '12px', width: '740px', maxHeight: '90vh', display: 'flex', flexDirection: 'column', color: '#c9d1d9' }}>
        <div style={{ padding: '16px 20px', borderBottom: '1px solid #30363d', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <FileText size={22} style={{ color: '#eab308' }} />
            <div>
              <h3 style={{ fontSize: '1.1rem', fontWeight: '700', color: '#f0f6fc', margin: 0 }}>PROJECT CODE INTELLIGENCE REPORT</h3>
              <small style={{ color: '#8b949e' }}>Repository: ShopSphere (demo/ShopSphere)</small>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button onClick={downloadReport} style={{ background: '#238636', color: '#fff', border: 'none', borderRadius: '6px', padding: '6px 14px', fontSize: '0.8rem', fontWeight: '600', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Download size={14} /> Download MD
            </button>
            <button onClick={onClose} style={{ background: 'transparent', border: 'none', color: '#8b949e', cursor: 'pointer' }}><X size={20} /></button>
          </div>
        </div>

        <div style={{ flex: 1, padding: '24px', overflowY: 'auto', fontSize: '0.85rem', lineHeight: '1.6' }}>
          <section style={{ marginBottom: '20px' }}>
            <h4 style={{ color: '#58a6ff', fontSize: '1rem', borderBottom: '1px solid #30363d', paddingBottom: '4px', marginBottom: '8px' }}>1. Executive Summary</h4>
            <p>ShopSphere repository passes all baseline Project Twin intelligence checks with an overall readiness score of <strong>88/100</strong>. No breaking API route contract regressions were detected.</p>
          </section>

          <section style={{ marginBottom: '20px' }}>
            <h4 style={{ color: '#58a6ff', fontSize: '1rem', borderBottom: '1px solid #30363d', paddingBottom: '4px', marginBottom: '8px' }}>2. Repository Statistics</h4>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '10px', textAlign: 'center' }}>
              <div style={{ background: '#0d1117', padding: '8px', borderRadius: '6px', border: '1px solid #30363d' }}>
                <strong style={{ fontSize: '1.1rem', color: '#f0f6fc' }}>428</strong>
                <div style={{ fontSize: '0.7rem', color: '#8b949e' }}>Files</div>
              </div>
              <div style={{ background: '#0d1117', padding: '8px', borderRadius: '6px', border: '1px solid #30363d' }}>
                <strong style={{ fontSize: '1.1rem', color: '#f0f6fc' }}>61,240</strong>
                <div style={{ fontSize: '0.7rem', color: '#8b949e' }}>Lines of Code</div>
              </div>
              <div style={{ background: '#0d1117', padding: '8px', borderRadius: '6px', border: '1px solid #30363d' }}>
                <strong style={{ fontSize: '1.1rem', color: '#f0f6fc' }}>38</strong>
                <div style={{ fontSize: '0.7rem', color: '#8b949e' }}>APIs</div>
              </div>
              <div style={{ background: '#0d1117', padding: '8px', borderRadius: '6px', border: '1px solid #30363d' }}>
                <strong style={{ fontSize: '1.1rem', color: '#f0f6fc' }}>46</strong>
                <div style={{ fontSize: '0.7rem', color: '#8b949e' }}>Dependencies</div>
              </div>
            </div>
          </section>

          <section style={{ marginBottom: '20px' }}>
            <h4 style={{ color: '#58a6ff', fontSize: '1rem', borderBottom: '1px solid #30363d', paddingBottom: '4px', marginBottom: '8px' }}>5. Duplicate Code Detection</h4>
            <div style={{ background: '#0d1117', border: '1px solid #a855f766', padding: '12px', borderRadius: '6px' }}>
              <strong style={{ color: '#c084fc' }}>LEVEL 4: Functional & Structural Duplication (87% match)</strong>
              <p style={{ margin: '4px 0', color: '#c9d1d9' }}><code>backend/payments/PaymentValidator.ts</code> lines 1-6 vs <code>backend/orders/OrderValidator.ts</code> lines 1-6.</p>
              <span style={{ color: '#38bdf8' }}>Recommendation: Extract shared validation logic into a centralized ValidationService.</span>
            </div>
          </section>

          <section style={{ marginBottom: '20px' }}>
            <h4 style={{ color: '#58a6ff', fontSize: '1rem', borderBottom: '1px solid #30363d', paddingBottom: '4px', marginBottom: '8px' }}>9. Change Impact Analysis</h4>
            <p>AuthService changes affect 18 components, 7 APIs, and 12 unit test suites.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
